version: "3"
services:
  php:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: OpenVBX
      MYSQL_USER: openvbxuser
      MYSQL_PASSWORD: asdf

volumes:
  db_data:
